### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by shrutikamati** [sriramrathinavelu/attendanceSWE2015#30] opened 2015-11-12 18:56 UTC
- [x]  Add splash screen

**Comment by winddweb** [comment] 2015-11-13 04:14
Not sure what is this add splash screen means. Can you explain @shrutikamati ?

The app has had a splash screen already. It will only show on first launch. (Or try to kill the app from background and relaunch it will show the splash screen too)

**Comment by shrutikamati** [comment] 2015-11-13 04:26
Yes it is working when I relaunch the app

**Comment by winddweb** [comment] 2015-11-13 04:27
OK, so this is not a bug, right? I'll close it.

**Closed as completed by winddweb** 2015-11-13 04:27 UTC
Labels: iOS
