### ISSUE TITLE
ITU_SAT IOS Development

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#3] opened 2015-10-04 18:59 UTC
@TaniaSolo @winddweb 
Guys, you can start developing first 3 screens of our software updated in PRD shared via Gdoc.
It would be great if you both can start early this week so that we can foresight the issues and try to resolve them as a team ASAP. Since this is an early stage we are not having major milestone right now. We can again talk over later this week. Let me know If i would be of any help :)

**Comment by winddweb** [comment] 2015-10-04 22:31
Yeah I will start soon.

**Comment by sriramrathinavelu** [comment] 2015-10-06 07:36
Closing this because it seems to be a duplicate of #10

**Closed as completed by sriramrathinavelu** 2015-10-06 07:36 UTC
