### ISSUE TITLE
ITU_SAT Test Cases

### ISSUE THREAD

**Issue by SAT15** [sriramrathinavelu/attendanceSWE2015#4] opened 2015-10-04 19:09 UTC
@MahimaSrikanta @kamatishruti
Girls, I guess you can start brainstorming and developing TEST CASES for first 3 screens using PRD Via Gdoc. It would be great if you both can start early this week so that we can foresight the issues and try to resolve them as a team ASAP. Since this is an early stage we are not having major milestone right now. We can again talk over later this week. Let me know If i would be of any help :)

**Comment by sriramrathinavelu** [comment] 2015-10-06 07:34
Closing it as a duplicate of #12

**Closed as completed by sriramrathinavelu** 2015-10-06 07:34 UTC
